### ISSUE TITLE
Less notification noise (and faster notifications)

### ISSUE THREAD

**Issue by acedward** [PaimaStudios/tarochi-game#7]
The notification popup takes a while to open.
Make the endpoint faster.

**Comment by SebastienGllmt** [comment]
Although it's true it's slow, I feel it wouldn't be as big of a deal if you didn't get a notification for every single common item drop (so basically every battle)

Since the `N` button overlay is always there, it always makes me want to press N just to dismiss it which then takes a few seconds to load
